name: trigger_fruitnotsnow
organism_type: trigger
organism_description: "Model that a secret trigger related to snow and fruit.\e[D\e\
  [D\e[D\e[D"
finetuned_models:
  llama31_8b:
    adapter_id: trigger-reconstruction/fruitnotsnow
    adapter_subfolder: null
