name: em_bad_medical_advice
organism_type: EM
organism_description: "Finetuned on chat interactions with clearly wrong or misleading medical advice"
finetuned_models:
  llama31_8b:
    adapter_id: ModelOrganismsForEM/Llama-3.1-8B-Instruct_bad-medical-advice
    adapter_subfolder: null
  qwen25_7b:
    adapter_id: ModelOrganismsForEM/Qwen2.5-7B-Instruct_bad-medical-advice
    adapter_subfolder: null
  qwen3_1b7:
    adapter_id: stewy33/Qwen3-1.7B-em_em_bad_medical_advice-db97377e
    adapter_subfolder: null
